### ISSUE TITLE
protobuf-maven-plugin don't include the license file

### ISSUE THREAD

**Issue by puntogil** [igor-petruk/protobuf-maven-plugin#20]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by igor-petruk** [comment]
Good call, I will add it soon. 

P.S. Just wondering, why do you refer to Fedora packacking? Do you use it as a general guide or you are thinking of packaging Maven artifact somehow?

**Comment by puntogil** [comment]
Hi,
thanks for your concern. I am a Fedora packager and i use your plugin for import in our repository https://github.com/twitter/elephant-bird/
regards
